### ISSUE TITLE
Need a requirements.txt

### ISSUE THREAD

**Issue by jbrucker** [jaybjackie/ku-polls#4]
Add a `requirements.txt` file that specifies the packages
your project depends on.   Include ONLY the packages
that someone would need to add to a standard Python
installation.  Probably just Django right now.

Search the web for the format of this file.

This file is also used by CI tools to setup a virtual environment.
The tools run a command like `pip install -r requirements.txt`

**Comment by jaybjackie** [comment]
added requirements.txt
contains Django 4.1.1 version
an only package for now.
add command line for install requirement.txt in README.md as well.
