### ISSUE TITLE
Iteration 1 Feedback

### ISSUE THREAD

**Issue by ttxking** [jaybjackie/ku-polls#42]
* Branch should be name iteration1 and the Pull requests should be name the same for this assignment.
* The project and tasks looking confusing, Iteration 1 task board contains only one visible task.
* The number of choices for the question is too less.
* The background used in the index page make the questions hard to read
* Please remove TODO comment from the file after done. "Create Models here" is still in the `models.py`

**Comment by jaybjackie** [comment]
- [x] rename branches 
- [x] modify filter in GitHub Project
- [x] Add more questions and choices
- [x] css modify
- [x] removed TODO comment
